#!/usr/bin/env sh

### Script to update Plex Media Server to the latest FreeBSD version
### Put the script in your $HOME/bin directory i.e.
### and make it executable : chmod +x $HOME/bin/plexupdate

INSTALLED=$(
	/usr/local/share/plexmediaserver/Plex_Media_Server --version \
	| sed 's/v//'
	)
VERSION=$(
	curl -q --no-progress-meter \
	https://plex.tv/downloads/details/1\?build\=freebsd-x86_64\&channel\=16\&distro\=freebsd \
	| awk -F"\"" '/Release id/ {print $4}'
	)

ARCH="FreeBSD-amd64"
PLEX_TMP="PlexMediaServer-${VERSION}"
PLEX_DIR="plexmediaserver"
PLEX_DIR_OLD="plexmediaserver_old"
PLEX_PATH="/usr/local/share"
SUDO="doas"
ARCHIVE="PlexMediaServer-${VERSION}-${ARCH}.tar.bz2"
SRC="/usr/local/src"
USER=$USER

if [ "$USER" != "root" ]; then
	echo "You must be root to run this script"
	echo "Exiting ..."
	exit 0
else

 service plexmediaserver status >/dev/null 2>&1
	PROCESS=$?

	if [ "$INSTALLED" == "$VERSION" ]; then
		echo "Running : $INSTALLED"
		echo "Latest  : $VERSION"
		echo ""
		echo -e "No news is good news"
		echo ""
	else
		echo "Running : $INSTALLED"
		echo "Latest  : $VERSION"
		echo "Update available, proceed ? (Y/n)"
		read ANSWER

		case $ANSWER in 
			n) 
			exit 0
			;;
      
			*)
			echo "Download ..."
			curl -q --no-progress-meter --output-dir ${SRC} -o ${ARCHIVE} https://downloads.plex.tv/plex-media-server-new/${VERSION}/freebsd/${ARCHIVE}
			echo "----"
			echo "Decompress ..."
			tar -xvf ${SRC}/${ARCHIVE} -C ${SRC} >/dev/null 2>&1
			mv ${SRC}/${PLEX_TMP} ${SRC}/${PLEX_DIR}
			rm ${SRC}/${ARCHIVE} #PlexMediaServer-${VERSION}-${ARCH}.tar.bz2
			echo "----"
			if [ "$PROCESS" -eq "0" ]; then
				echo "service stop ..."
				service plexmediaserver stop >/dev/null 2>&1
				echo "----"
			fi
			echo "update in progress ..."
			sleep 2
			;;
		esac

	# We remove previous plex_old dir
	# We move current plex directory to plex_old dir
	# We move new plex directory into plex path
	# Change the owner plex:plex for plex directory
		if [ -d "${PLEX_PATH}/${PLEX_DIR_OLD}" ]; then
			rm -rf ${PLEX_PATH}/${PLEX_DIR_OLD}
			mv ${PLEX_PATH}/${PLEX_DIR} ${PLEX_PATH}/${PLEX_DIR_OLD}
			mv ${SRC}/${PLEX_DIR} ${PLEX_PATH}/
			ln -s "${PLEX_PATH}/${PLEX_DIR}/Plex Media Server" "${PLEX_PATH}/${PLEX_DIR}/Plex_Media_Server"
			chown -R plex:plex ${PLEX_PATH}/${PLEX_DIR}
			echo "----"
			echo "service start ..."
			service plexmediaserver start >/dev/null 2>&1
		else
			mv ${PLEX_PATH}/${PLEX_DIR} ${PLEX_PATH}/${PLEX_DIR_OLD}
			mv ${SRC}/${PLEX_DIR} ${PLEX_PATH}/
			ln -s "${PLEX_PATH}/${PLEX_DIR}/Plex Media Server" "${PLEX_PATH}/${PLEX_DIR}/Plex_Media_Server"
			chown -R plex:plex ${PLEX_PATH}/${PLEX_DIR}
			echo "service start ..."
			service plexmediaserver start >/dev/null 2>&1
		fi
	fi
fi
